In [1]:
import re
import numpy as np
from scipy.spatial.distance import cdist

#список списков с токенизированными словами предложений из файла sentences.txt
source = list()
for line in open("sentences.txt", mode='r').readlines():
    source.append(list(filter(None, re.split('[^a-z]', line.lower()))))

In [2]:
uniqWords = set()
for sentence in source:
    for w in sentence:
        uniqWords.add(w)
uniq = list(uniqWords)

print("0: ", uniq[0])

0:  are


In [3]:
matrix = np.zeros((len(source), len(uniqWords)), dtype=np.int32)
print(matrix)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [4]:
def word_count(word, word_list):
    count = 0
    for w in word_list:
        if w == word:
            count += 1

    return count


In [5]:
for i in range(0, len(source)):
    for j in range(0, len(uniq)):
        matrix[i, j] = word_count(uniq[j], source[i])



In [6]:
#вычисляем косинусное расстояние между векторами
cos_distance = cdist(matrix[0:1], matrix[1:], metric='cosine')

In [7]:
# сортируем предложение в зависимости от их косинусного расстояния
sorted_result = list()
for v in range(0, len(cos_distance[0])):
    sorted_result.append((v+1, cos_distance[0, v]))

sorted_result.sort(key=lambda x:x[1])

for x in sorted_result:
    print(x[1],x[0], source[x[0]])


0.7327387580875756 6 ['domestic', 'cats', 'are', 'similar', 'in', 'size', 'to', 'the', 'other', 'members', 'of', 'the', 'genus', 'felis', 'typically', 'weighing', 'between', 'and', 'kg', 'and', 'lb']
0.7770887149698589 4 ['in', 'one', 'people', 'deliberately', 'tamed', 'cats', 'in', 'a', 'process', 'of', 'artificial', 'selection', 'as', 'they', 'were', 'useful', 'predators', 'of', 'vermin']
0.8250364469440586 21 ['the', 'fifth', 'major', 'update', 'to', 'mac', 'os', 'x', 'leopard', 'contains', 'such', 'a', 'mountain', 'of', 'features', 'more', 'than', 'by', 'apple', 's', 'count']
0.8328165362273942 10 ['cat', 'command', 'is', 'one', 'of', 'the', 'basic', 'commands', 'that', 'you', 'learned', 'when', 'you', 'started', 'in', 'the', 'unix', 'linux', 'world']
0.8396432548525454 12 ['when', 'you', 'type', 'simply', 'cat', 'command', 'without', 'any', 'arguments', 'it', 'just', 'receives', 'the', 'stdin', 'content', 'and', 'displays', 'it', 'in', 'the', 'stdout']
0.8406361854220809 16 ['sinc